const BASE_PRODUCTS = [
  {
    id: 1,
    name: "Fallout 76",
    title: "Fallout 76",
    price: 0.59,
    image: "/battlefield_6.jpg",
    images: ["/battlefield_6.jpg", "/battlefield6-2.jpg"],
    platform: "xbox",
    platformLabel: "Xbox Live",
    type: "Product key",
    edition: "Standard",
    delivery: "Instant",
    activationRegion: "Global",
    currency: "$",
    seller: {
      id: "S1",
      name: "CodesMarket",
      avatar: "/avt.jpg",
      isOnline: true,
      badge: "🛡️",
      tier: "Legendary",
      rating: 5,
      successRate: 97.51,
      totalFeedbacks: 1012,
      timezone: "UTC +00:00",
      totalSales: 115101,
      positiveFeedbacks: 99.58,
      negativeFeedbacks: 6.93,
    },
  },
  {
    id: 2,
    name: "Cyberpunk 2077 Ultimate Edition",
    title: "Cyberpunk 2077 Ultimate Edition",
    price: 0.82,
    image: "/cyberpunk_2077.jpg",
    images: ["/cyberpunk_2077.jpg"],
    platform: "pc",
    platformLabel: "Steam",
    type: "Product key",
    edition: "Ultimate",
    delivery: "Instant",
    activationRegion: "Worldwide",
    currency: "$",
    seller: {
      id: "S2",
      name: "GameKeys Pro",
      avatar: "/spacex.jpg",
      isOnline: false,
      badge: "⭐",
      tier: "Elite",
      rating: 4,
      successRate: 95.2,
      totalFeedbacks: 1542,
      timezone: "UTC +02:00",
      totalSales: 45230,
      positiveFeedbacks: 97.8,
      negativeFeedbacks: 2.2,
    },
  },
  {
    id: 3,
    name: "Settlement Survival",
    title: "Settlement Survival",
    price: 0.65,
    image: "/battlefield_6.jpg",
    images: ["/battlefield_6.jpg"],
    platform: "playstation",
    platformLabel: "PlayStation Store",
    type: "Product key",
    edition: "Standard",
    delivery: "Instant",
    activationRegion: "Global",
    currency: "$",
    seller: {
      id: "S3",
      name: "DigitalGames",
      avatar: "/seller3.jpg",
      isOnline: true,
      badge: "🏆",
      tier: "Master",
      rating: 5,
      successRate: 98.75,
      totalFeedbacks: 8921,
      timezone: "UTC -05:00",
      totalSales: 234567,
      positiveFeedbacks: 99.12,
      negativeFeedbacks: 0.88,
    },
  },
  {
    id: 4,
    name: "Beholder Conductor",
    title: "Beholder Conductor",
    price: 0.65,
    image: "/battlefield_6.jpg",
    images: ["/battlefield_6.jpg"],
    platform: ["pc", "playstation", "xbox"],
    platformLabel: "Multi-platform",
    type: "Product key",
    edition: "Complete",
    delivery: "Instant",
    activationRegion: "Global",
    currency: "$",
    seller: {
      id: "S4",
      name: "VoidKeys",
      avatar: "/avt.jpg",
      isOnline: true,
      badge: "⚔️",
      tier: "Elite",
      rating: 4.8,
      successRate: 99.0,
      totalFeedbacks: 5420,
      timezone: "UTC +01:00",
      totalSales: 15400,
      positiveFeedbacks: 98.5,
      negativeFeedbacks: 1.5,
    },
  },
  {
    id: 5,
    name: "Nidhogg 2",
    title: "Nidhogg 2",
    price: 0.58,
    image: "/battlefield_6.jpg",
    images: ["/battlefield_6.jpg"],
    platform: ["nintendo", "xbox"],
    platformLabel: "Switch / Xbox",
    type: "Product key",
    edition: "Standard",
    delivery: "Instant",
    activationRegion: "Global",
    currency: "$",
    seller: {
      id: "S1",
      name: "CodesMarket",
      avatar: "/avt.jpg",
      isOnline: true,
    },
  },
  {
    id: 6,
    name: "Escape from Ever After",
    title: "Escape from Ever After",
    price: 500,
    image: "/battlefield_6.jpg",
    images: ["/battlefield_6.jpg"],
    platform: "pc",
    platformLabel: "Steam",
    type: "Product key",
    edition: "Deluxe",
    delivery: "Instant",
    activationRegion: "Global",
    currency: "$",
    seller: {
      id: "S2",
      name: "GameKeys Pro",
      avatar: "/spacex.jpg",
    },
  },
  {
    id: 7,
    name: "Caravan SandWitch",
    title: "Caravan SandWitch",
    price: 300,
    image: "/battlefield_6.jpg",
    images: ["/battlefield_6.jpg"],
    platform: "pc",
    platformLabel: "Epic Games",
    type: "Product key",
    edition: "Standard",
    delivery: "Instant",
    activationRegion: "Global",
    currency: "$",
    seller: {
      id: "S3",
      name: "DigitalGames",
      avatar: "/seller3.jpg",
    },
  },
  {
    id: 8,
    name: "Batman Arkham Origins",
    title: "Batman Arkham Origins",
    price: 1.66,
    image: "/battlefield_6.jpg",
    images: ["/battlefield_6.jpg"],
    platform: "pc",
    platformLabel: "Steam",
    type: "Product key",
    edition: "Standard",
    delivery: "Instant",
    activationRegion: "Global",
    currency: "$",
    seller: {
      id: "S4",
      name: "VoidKeys",
      avatar: "/avt.jpg",
    },
  },
];

const EXTRA_PRODUCT_TITLES = [
  "The Last Campfire",
  "Risk of Rain 2",
  "Hades II",
  "Dead Cells Return",
  "Noita Ultimate",
  "Frostpunk Complete",
  "Cuphead Deluxe",
  "The Ascent",
  "Celeste Gold",
  "Stardew Valley Plus",
  "Hollow Knight Silksong",
  "Remnant II",
  "Sea of Stars",
  "Dave the Diver",
  "Valheim",
  "Astroneer",
  "Grounded",
  "A Plague Tale",
  "Sifu",
  "Tunic",
  "Eiyuden Chronicle",
  "Blasphemous II",
  "Atlas Fallen",
  "Dredge",
  "Atomic Heart",
  "Lords of the Fallen",
  "Lies of P",
  "Payday 3",
  "Forza Horizon 5",
  "Starfield",
];

const EXTRA_PLATFORMS = ["pc", "xbox", "playstation", "nintendo"];
const EXTRA_PLATFORM_LABELS = {
  pc: "Steam",
  xbox: "Xbox Live",
  playstation: "PlayStation Store",
  nintendo: "Nintendo eShop",
};

const EXTRA_PRODUCTS = EXTRA_PRODUCT_TITLES.map((title, index) => {
  const id = BASE_PRODUCTS.length + index + 1;
  const platform = EXTRA_PLATFORMS[index % EXTRA_PLATFORMS.length];

  return {
    id,
    name: title,
    title,
    price: Number((0.99 + (index % 12) * 0.45).toFixed(2)),
    image: "/cyberpunk_2077.jpg",
    images: ["/cyberpunk_2077.jpg"],
    platform,
    platformLabel: EXTRA_PLATFORM_LABELS[platform],
    type: "Product key",
    edition: index % 3 === 0 ? "Deluxe" : "Standard",
    delivery: "Instant",
    activationRegion: "Global",
    currency: "$",
    seller: {
      id: `SX${(index % 4) + 1}`,
      name: ["CodesMarket", "GameKeys Pro", "DigitalGames", "VoidKeys"][
        index % 4
      ],
      avatar: "/avt.jpg",
      isOnline: index % 2 === 0,
    },
  };
});

const ALL_PRODUCTS = [...BASE_PRODUCTS, ...EXTRA_PRODUCTS];

// Transform internal data into the exported formats
export const mockProducts = ALL_PRODUCTS.reduce((acc, product) => {
  acc[product.id] = {
    data: {
      id: product.id.toString(),
      name: product.name,
      type: product.type,
      platform: product.platformLabel,
      edition: product.edition,
      delivery: product.delivery,
      activationRegion: product.activationRegion,
      price: product.price,
      currency: product.currency,
      images: product.images,
    },
    seller: {
      ...product.seller,
      // Provide defaults for missing seller info
      isOnline: product.seller.isOnline ?? false,
      badge: product.seller.badge ?? "⭐",
      tier: product.seller.tier ?? "Pro",
      rating: product.seller.rating ?? 4.5,
      successRate: product.seller.successRate ?? 95,
      totalFeedbacks: product.seller.totalFeedbacks ?? 100,
      timezone: product.seller.timezone ?? "UTC +00:00",
      totalSales: product.seller.totalSales ?? 1000,
      positiveFeedbacks: product.seller.positiveFeedbacks ?? 95,
      negativeFeedbacks: product.seller.negativeFeedbacks ?? 5,
    },
  };
  return acc;
}, {});

export const listingProducts = ALL_PRODUCTS.map((product) => ({
  id: product.id,
  title: product.title,
  price: product.price,
  image: product.image,
  platform: product.platform,
}));
